name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            APP_DIR=elven-sre-api

            if [ -d "$APP_DIR" ]; then
              echo "Diretório $APP_DIR já existe, fazendo pull..."
              cd $APP_DIR
              git pull origin master
            else
              echo "Diretório $APP_DIR não existe, clonando repositório..."
              git clone https://github.com/VitoorFranca/elven-sre-api.git $APP_DIR
              cd $APP_DIR
            fi

            cat <<EOF > .env
            NODE_ENV=production
            PORT=3000
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            OTEL_EXPORTER_OTLP_ENDPOINT=${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
            LOG_LEVEL=${{ secrets.LOG_LEVEL }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DOMAIN=${{ secrets.DOMAIN }}
            SSL_EMAIL=${{ secrets.SSL_EMAIL }}
            EOF

            docker compose down
            docker compose up --build -d