name: Build & Deploy to EC2

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ggj8efv5gssrcdwjdzwidxei/elven-sre-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t $IMAGE_NAME:latest --target production .

      - name: Push para o Docker Hub
        run: |
          docker push $IMAGE_NAME:latest

      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull $IMAGE_NAME:latest
            docker stop elven-sre-api || true
            docker rm elven-sre-api || true
            docker run -d \
              --name elven-sre-api \
              -e NODE_ENV=production \
              -e PORT=3000 \
              -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}' \
              -e OTEL_EXPORTER_OTLP_ENDPOINT='${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}' \
              -e LOG_LEVEL='${{ secrets.LOG_LEVEL }}' \
              -e DB_HOST='${{ secrets.DB_HOST }}' \
              -e DB_PORT='${{ secrets.DB_PORT }}' \
              -e DB_USER='${{ secrets.DB_USER }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e DB_NAME='${{ secrets.DB_NAME }}' \
              $IMAGE_NAME:latest
